validation_rules:
  # Fields required for PDF generation
  pdf_fields:
    - invoice_number
    - receive_date
    - party_name
    - location
    - boxes
    - weight
    - transporter
    - eway_bill

  field_types:
    invoice_number: str
    receive_date: date
    time: time
    brand: str
    party_name: str
    location: str
    boxes: int
    transporter: str
    transit_time: date
    eway_bill: str
    pin_code: int
    amount: float
    weight: str
    lr_no: str
    remark: str
    status: str
    delivery_date: date

  # Excel column to database field mapping
  column_mapping:
    INVOICE  NO: invoice_number
    RECEIVE DATE: receive_date
    TIME: time
    BRAND: brand
    '                PARTY NAME': party_name
    '        LOCATION': location
    'BOX   ': boxes
    TRANSPORTER: transporter
    TRANSICT TIME: transit_time
    'E-WAYBILL ': eway_bill
    'PIN CODE': pin_code
    AMT: amount
    KG: weight
    'TRNS LR NO.': lr_no
    REMARK: remark
    STATUS: status
    'DELIVERY DATE': delivery_date

  # Fields to show on PDF
  pdf_mapping:
    invoice_number: INVOICE  NO
    receive_date: RECEIVE DATE
    party_name: '                PARTY NAME'
    location: '        LOCATION'
    boxes: 'BOX   '
    weight: KG
    transporter: TRANSPORTER
    eway_bill: 'E-WAYBILL '

lr_generation:
  items_per_page: 3
  id_pattern: "{branch_code}{YYMMDD}{sequence:04d}"
  sequence_reset: daily

database:
  table_name: shipment_records
  batch_size: 100
  retry_attempts: 3
  retry_delay_seconds: 5

watch_settings:
  patterns: ["*.xlsx", "*.xls"]
  ignore_patterns: ["~$*", "*.tmp"]
  stabilization_seconds: 5
  delete_after_processing: true

print_settings:
  enabled: true
  printer_name: "Microsoft Print to PDF"  # Default to PDF if no printer
  copies: 1
  timeout_seconds: 30
